// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CY1YcJJ9ofYfE9hF8UHf93RK4NKV36k',
    appId: '1:661913552077:web:dcb56e46165b87037d5584',
    messagingSenderId: '661913552077',
    projectId: 'flutter-login-6dd08',
    authDomain: 'flutter-login-6dd08.firebaseapp.com',
    storageBucket: 'flutter-login-6dd08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69Two01GFWIKwOZqiQ50FTbHaDgFX8pU',
    appId: '1:661913552077:android:f21f0a961be2e57c7d5584',
    messagingSenderId: '661913552077',
    projectId: 'flutter-login-6dd08',
    storageBucket: 'flutter-login-6dd08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRabvYDyExEIYymvM-U_-1B74jbvm__H4',
    appId: '1:661913552077:ios:d8708692ada0910a7d5584',
    messagingSenderId: '661913552077',
    projectId: 'flutter-login-6dd08',
    storageBucket: 'flutter-login-6dd08.firebasestorage.app',
    androidClientId: '661913552077-7ni6lv29d7gv7aerqkmjgofo4fs6kodr.apps.googleusercontent.com',
    iosClientId: '661913552077-jucomsm3kfi39v21ktbv07ik3vld29nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCapstone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRabvYDyExEIYymvM-U_-1B74jbvm__H4',
    appId: '1:661913552077:ios:d8708692ada0910a7d5584',
    messagingSenderId: '661913552077',
    projectId: 'flutter-login-6dd08',
    storageBucket: 'flutter-login-6dd08.firebasestorage.app',
    iosBundleId: 'com.example.projectCapstone1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-CY1YcJJ9ofYfE9hF8UHf93RK4NKV36k',
    appId: '1:661913552077:web:cfdb386a9fa45b627d5584',
    messagingSenderId: '661913552077',
    projectId: 'flutter-login-6dd08',
    authDomain: 'flutter-login-6dd08.firebaseapp.com',
    storageBucket: 'flutter-login-6dd08.firebasestorage.app',
  );
}